<?php

namespace upload\components\base;

use yii;
use common\models\App;
use yii\base\Exception;
use upload\components\helpers\Ip;
use upload\components\exception\BussinessLogicException;
use upload\components\errors\Code;

/**
 * Class Controller
 * @package upload\components\base
 */
class Controller extends yii\web\Controller
{
    /**
     * @var App $app
     */
    public $app;


    /**
     * @param yii\base\Action $action
     * @return bool
     * @throws Exception
     * @throws yii\web\BadRequestHttpException
     */
    public function beforeAction($action)
    {
        $app_key = Yii::$app->request->get('app_key');
        /** @var App $app */
        $app = App::findOne(['key' => $app_key]);
        if ($app === null) {
            throw new BussinessLogicException(Code::VALIDATE_APP_KEY_ERROR);
        }
        $this->validateIps($app->allowed_ips);
        $this->validateSignature($app->secret);
        $this->app = $app;
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    /**
     * 验证IP有效性
     *
     * @param $allowedIps
     * @return bool
     * @throws BussinessLogicException
     */
    public function validateIps($allowedIps)
    {
        $ip = Ip::getRemoteAddress();
        $ipRang = explode(',', $allowedIps);
        foreach ($ipRang as $v) {
            if (Ip::ip_in_range($ip, $v)) {
                return true;
            }
        }
        throw new BussinessLogicException(Code::VALIDATE_IP_ERROR);
    }

    /**
     * 验证签名
     *
     * @param $secret
     * @return bool
     * @throws BussinessLogicException
     */
    public function validateSignature($secret)
    {
        $params = Yii::$app->request->get();
        $signature = Yii::$app->request->get('signature');
        $timestamp = Yii::$app->request->get('timestamp');
        unset($params['signature']);
        unset($params['category_url_name']);
        // 生成签名
        ksort($params);
        $result = http_build_query($params);
        $md5 = md5($result . $secret);
        // 比对签名
        if ($md5 !== $signature) {
            throw new BussinessLogicException(Code::VALIDATE_SIGNATURE_ERROR);
        }
        if (time() >= $timestamp + Yii::$app->params['signatureExpires']) {
            throw new BussinessLogicException(Code::VALIDATE_SIGNATURE_EXPIRES_ERROR);
        }
        return true;
    }
}
